### ISSUE TITLE
[BRUKERHISTORIE] E-postvarsling som standardinnstilling i Datalandsbyen

### ISSUE THREAD

**Issue by livarb** [Informasjonsforvaltning/behov#620]
Som: bruker av Datalandsbyen
Ønsker jeg å: få e-postvarsling om viktige hendelser
Slik at: jeg får med meg når noe viktig skjer

Relatert til epos:

Lenke til design: 
Lenke til løsningsarkitektur:

Forretningsverdi (Kritisk/Viktig/Mindre viktig/Kjekt å ha):

I dag er alle e-postvarsel skrudd av som standard-innstilling. Dersom en bruker skal ha e-postvarsel, må det manuelt slås på av den enkelte brukeren. Brukere får kanskje ikke med seg dersom noe skjer, for eksempel om de får et svar på en post de har opprettet. Det er mange innstillinger, og e-postvarsel bør ikke skrus på for alt, men for noe bør det være skrudd på som standard.

**Forslag til hva e-postvarsel som skal være skrudd på som standard**
- Nye innlegg i emner du har oppretta
- Nye innlegg i emner du overvåker
- Nye innlegg i emner du har svart på
- Når du blir nevnt av andre

**I praksis betyr det at disse innstillingene er avkrysset:**
Overvåk - Watch topics you create
Overvåk - Watch topics that you reply to
Notifications - Når et nytt svar er lagt ut i et emne du overvåker --> Kun e-post
Notifications - "When someone mentions you" --> Kun e-post

Stemmer det at ingen emner blir overvåket automatisk?
Tenker dette er en forutsetning for å skru på e-postvarsel på emner en overvåker.

Hvordan gjør vi denne endringen med tanke på brukersamtykke?
I samtykke-teksten står det nederst: «Med mindre dette er eksplisitt endret i brukerinnstillingene dine, sendes det ikke ut e-post»

**Comment by livarb** [comment]
@ChristianeFrhlich : Veit du kva status er på saka? Var det slik at du sjekkar opp i korleis vi gjer det med samtykke?

**Comment by ChristianeFrhlich** [comment]
Har spurt Oddhild om rådføring. Avventer svar


Vennlig hilsen

Christiane Andrea Fröhlich
Rådgiver, seksjon for informasjonsforvaltning

Mob: +47 908 27 835
Grev Wedels Plass 9, 0151 Oslo, NO

Digitaliseringsdirektoratet
Postboks 1382 Vika, 0114 Oslo, NO
-

***@***.***
www.digdir.no<https://eur03.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.digdir.no%2F&data=02%7C01%7C%7C717097a616294d0f12fa08d8379c76d1%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C637320492441409664&sdata=IFZvryCfq6Rcdl5aiBjIw3omMwjJqSHLYKZNCR7a5P0%3D&reserved=0>



Fra: Livar Bergheim ***@***.***>
Sendt: mandag 23. august 2021 09:15
Til: Informasjonsforvaltning/behov ***@***.***>
Kopi: Fröhlich, Christiane Andrea ***@***.***>; Mention ***@***.***>
Emne: Re: [Informasjonsforvaltning/behov] [BRUKERHISTORIE] E-postvarsling som standardinnstilling i Datalandsbyen (#620)


@ChristianeFrhlich<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FChristianeFrhlich&data=04%7C01%7C%7Cb305ba1bd56f41e5a02a08d96605b451%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C637652996955268219%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PuULJEkJv%2BI%2FyjC7x8W6rB4a4qRpoYj95w6EezB%2FPJ4%3D&reserved=0> : Veit du kva status er på saka? Var det slik at du sjekkar opp i korleis vi gjer det med samtykke?

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FInformasjonsforvaltning%2Fbehov%2Fissues%2F620%23issuecomment-903506094&data=04%7C01%7C%7Cb305ba1bd56f41e5a02a08d96605b451%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C637652996955278174%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hDb6qpq1mQvyieXA5N%2BR0DC9m0Ieloy2vhDV0P7HPb8%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAQSZXRAZX7MJY7CJKJMC6MDT6HYOZANCNFSM5CAMOVWA&data=04%7C01%7C%7Cb305ba1bd56f41e5a02a08d96605b451%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C637652996955278174%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Mwg4CmvIYsoIl14Iqv7J%2BYrCClBR5%2FUp%2BLPy7Qg8cZg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cb305ba1bd56f41e5a02a08d96605b451%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C637652996955288125%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=6yh1zNKL4Rmd8icrLq1eNqTTudModU1dWwymE%2B%2Bnphc%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7C%7Cb305ba1bd56f41e5a02a08d96605b451%7C008e560f08af4ceca056b35447503991%7C1%7C0%7C637652996955288125%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=upwcYVSyex09k9508n6Murt9TfS%2B1Fl7BeKXQQJfVxA%3D&reserved=0>.

**Comment by livarb** [comment]
@ChristianeFrhlich : Høyrt noko meir frå Oddhild?

**Comment by livarb** [comment]
Vi testa for ei stund sidan korleis innstillingane kan endrast i NodeBB. Dersom ein endrar standard-innstillingane i Datalandsbyen, så påverkar det alle brukarar - med unntak av dei som allereie har endra innstillingane sine på eiga hand slik at dei ikkje lenger samsvarar med standardinnstillingane.

**Comment by livarb** [comment]
Posta om dette i Datalandsbyen i fjor, og har ikkje fått nokon tilbakemeldingar: https://datalandsbyen.norge.no/topic/69/e-postvarsling-i-datalandsbyen

**Comment by livarb** [comment]
Oppdaterte beskrivelsen.
Fjerna varsling skrudd på for "Notifications - Når et innlegg er redigert i et emne du overvåker"
La til varsling for "When someone mentions you"

**Comment by ChristianeFrhlich** [comment]
- Månedlig oppdatering
- Infobrev er klart

**Comment by livarb** [comment]
Endringar er gjort, e-post er sendt ut til alle brukarane og melding er posta i Datalandsbyen: https://datalandsbyen.norge.no/topic/205/e-postvarsling-er-skrudd-p%C3%A5
